name: Testops Report WEEKLY 

# Sat. @4am UTC
on:
  schedule:
    - cron:  "0 4 * * 6" 
  workflow_dispatch:

jobs:
  deploy:
    uses: mozilla-mobile/test-dashboard/.github/workflows/update-testops-db.yml@reusable-workflow
    with:
      project_name: "ALL"
      frequency: "Weekly"
      is_update_db: true