name: Testops Report PUSH 

on:
  push:
    branches:
      - reusable-workflow 

jobs:
  deploy:
    uses: mozilla-mobile/test-dashboard/.github/workflows/update-testops-db.yml
      with:
        project_name: "fenix"
        frequency: "Daily"
        is_update_db: true