name: Testops Report PUSH 

on:
  push:
    branches:
      - reusable-workflow 

jobs:
  deploy:
    uses: clarmso/test-dashboard/.github/workflows/update-testops-db.yml@reusable-workflow
    with:
      project_name: "fenix"
      frequency: "Daily"
      is_update_db: true